### ISSUE TITLE
sklearn module not found

### ISSUE THREAD

**Issue by ayushagg1306** [benbogin/spider-schema-gnn-global#9]
I have tried to install as per the document, but when I ran the train model command it gives the sklearn module error.
File "/home/user/ln2sql/venv/lib/python3.6/site-packages/allennlp/training/metrics/conll_coref_scores.py", line 5, in <module>
    from sklearn.utils.linear_assignment_ import linear_assignment
ModuleNotFoundError: No module named 'sklearn.utils.linear_assignment_'

**Comment by benbogin** [comment]
Hi, this error doesn't seem to be due to any of this repository code, probably some versioning issue. Did you install all packages with their version (as defined in `requirements.txt`)? Also, you can check out some suggested solutions to this issue on the web, for example: https://github.com/facebookresearch/UnsupervisedQA/issues/13
